version: '3.6'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/ping
    volumes:
      - ./frontend:/usr/src/app
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_URL=mongodb://mongodb:27017/testdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./backend:/usr/src/app
  
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    # volumes:
    #   - redis-data:/data
  
volumes:
  mongo-volume:
  # data:
